#Port Configuration
server:
  port: 8080

#DB Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/caching
    username: root
    password: MySQL@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: spring-boot-caching